### ISSUE TITLE
failed to compile with gcc-8.2.1

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#31]
make[3]: Entering directory '/root/rpmbuild/BUILD/mstflint-4.11.0/ext_libs/iniParser'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../.. -I. -I../.. -I../../ -I../../common   -W -Werror -g -MP -MD -fPIC  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DMST_UL -c -o iniparser.lo iniparser.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I. -I../.. -I../../ -I../../common -W -Werror -g -MP -MD -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DMST_UL -c iniparser.c  -fPIC -DPIC -o .libs/iniparser.o
iniparser.c: In function 'iniparser_load':
iniparser.c:639:30: error: '%s' directive writing up to 1024 bytes into a region of size between 0 and 1024 [-Werror=format-overflow=]
             sprintf(tmp, "%s:%s", section, key);
                              ^~            ~~~
In file included from /usr/include/stdio.h:873,
                 from iniparser.h:58,
                 from iniparser.c:52:
/usr/include/bits/stdio2.h:36:10: note: '__builtin___sprintf_chk' output between 2 and 2050 bytes into a destination of size 1025
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:417: iniparser.lo] Error 1
make[3]: Leaving directory '/root/rpmbuild/BUILD/mstflint-4.11.0/ext_libs/iniParser'
make[3]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/root/rpmbuild/BUILD/mstflint-4.11.0/ext_libs/iniParser'

**Comment by HonggangLI** [comment]
Issue had been fixed in latest upstream release. Close it.
