### ISSUE TITLE
mstflint-4.31.0 fails to build from source on RHEL-10.0, error in fwctrl.c

### ISSUE THREAD

**Issue by gobenji** [Mellanox/mstflint#1133]
On a RHEL-10.0 (beta) system, doing
```
dnf builddep mstflint
tar -xf mstflint-4.31.0-1.tar.gz
cd mstflint-4.31.0
./configure
make
```
fails because of the following error:
```
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../include/mtcr_ul -I../common -I../dev_mgt  -W -Wall -g -MP -MD -fPIC -DMTCR_API="" -DMST_UL -g -O2 -DNO_RDMEM -DMST_UL -MT libmtcr_ul_la-fwctrl.lo -MD -MP -MF .deps/libmtcr_ul_la-fwctrl.Tpo -c -o libmtcr_ul_la-fwctrl.lo `test -f 'fwctrl.c' || echo './'`fwctrl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I../include/mtcr_ul -I../common -I../dev_mgt -W -Wall -g -MP -MD -fPIC -DMTCR_API= -DMST_UL -g -O2 -DNO_RDMEM -DMST_UL -MT libmtcr_ul_la-fwctrl.lo -MD -MP -MF .deps/libmtcr_ul_la-fwctrl.Tpo -c fwctrl.c  -fPIC -DPIC -o .libs/libmtcr_ul_la-fwctrl.o
fwctrl.c: In function 'fwctl_control_access_register':
fwctrl.c:190:27: error: implicit declaration of function 'return_by_reg_status' [-Wimplicit-function-declaration]
  190 |             *reg_status = return_by_reg_status(cmd_status);
      |                           ^~~~~~~~~~~~~~~~~~~~
In file included from fwctrl.c:45:
fwctrl.c:195:56: error: implicit declaration of function 'm_err2str' [-Wimplicit-function-declaration]
  195 |                       reg_id, cmd_status, *reg_status, m_err2str(status));
      |                                                        ^~~~~~~~~
../include/mtcr_ul/fwctrl_ioctl.h:47:81: note: in definition of macro 'FWCTL_DEBUG_PRINT'
   47 |         printf("%s: %s %d: " format, FWCTL_ENV_VAR_DEBUG, __func__, __LINE__, ##arg); \
      |                                                                                 ^~~
../include/mtcr_ul/fwctrl_ioctl.h:47:16: warning: format '%s' expects argument of type 'char *', but argument 8 has type 'int' [-Wformat=]
   47 |         printf("%s: %s %d: " format, FWCTL_ENV_VAR_DEBUG, __func__, __LINE__, ##arg); \
      |                ^~~~~~~~~~~~~
fwctrl.c:194:5: note: in expansion of macro 'FWCTL_DEBUG_PRINT'
  194 |     FWCTL_DEBUG_PRINT(mf, "register id = 0x%x, command status = 0x%x, reg status code: 0x%x, reg status: %s\n",
      |     ^~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:589: libmtcr_ul_la-fwctrl.lo] Error 1
```
The same worked on RHEL-9.5. However it's possible to reproduce the failure on Fedora Core 41 by doing `make -C mtcr_ul/` to workaround #1132

**Comment by ogalbxela** [comment]
There is a list of supported OSes in the release note. RHEL-10.0 is not suppored yet.

**Comment by nkukard** [comment]
Same error building on Arch Linux

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I../include/mtcr_ul -I../common -I../dev_mgt -W -Wall -g -MP -MD -fPIC -DMTCR_API= -DMST_UL -g -O2 -DNO_RDMEM -DMST_UL -MT libmtcr_ul_la-fwctrl.lo -MD -MP -MF .deps/libmtcr_ul_la-fwctrl.Tpo -c fwctrl.c  -fPIC -DPIC -o .libs/libmtcr_ul_la-fwctrl.o
mtcr_ul_icmd_cif.c:286:9: warning: "CX8_HW_ID" redefined
  286 | #define CX8_HW_ID       542
      |         ^~~~~~~~~
In file included from ../include/mtcr_ul/mtcr.h:44,
                 from mtcr_icmd_cif.h:43,
                 from mtcr_ul_icmd_cif.c:43:
../include/mtcr_ul/mtcr_com_defs.h:103:9: note: this is the location of the previous definition
  103 | #define CX8_HW_ID 0x21e
      |         ^~~~~~~~~
mtcr_ul_icmd_cif.c:287:9: warning: "CX9_HW_ID" redefined
  287 | #define CX9_HW_ID       549
      |         ^~~~~~~~~
../include/mtcr_ul/mtcr_com_defs.h:104:9: note: this is the location of the previous definition
  104 | #define CX9_HW_ID 0x225
      |         ^~~~~~~~~
fwctrl.c: In function 'fwctl_control_access_register':
fwctrl.c:190:27: error: implicit declaration of function 'return_by_reg_status' [-Wimplicit-function-declaration]
  190 |             *reg_status = return_by_reg_status(cmd_status);
      |                           ^~~~~~~~~~~~~~~~~~~~
In file included from fwctrl.c:45:
fwctrl.c:195:56: error: implicit declaration of function 'm_err2str' [-Wimplicit-function-declaration]
  195 |                       reg_id, cmd_status, *reg_status, m_err2str(status));
      |                                                        ^~~~~~~~~
../include/mtcr_ul/fwctrl_ioctl.h:47:81: note: in definition of macro 'FWCTL_DEBUG_PRINT'
   47 |         printf("%s: %s %d: " format, FWCTL_ENV_VAR_DEBUG, __func__, __LINE__, ##arg); \
      |                                                                                 ^~~
../include/mtcr_ul/fwctrl_ioctl.h:47:16: warning: format '%s' expects argument of type 'char *', but argument 8 has type 'int' [-Wformat=]
   47 |         printf("%s: %s %d: " format, FWCTL_ENV_VAR_DEBUG, __func__, __LINE__, ##arg); \
      |                ^~~~~~~~~~~~~
fwctrl.c:194:5: note: in expansion of macro 'FWCTL_DEBUG_PRINT'
  194 |     FWCTL_DEBUG_PRINT(mf, "register id = 0x%x, command status = 0x%x, reg status code: 0x%x, reg status: %s\n",
      |     ^~~~~~~~~~~~~~~~~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I.. -I../include/mtcr_ul -I../common -I../dev_mgt -W -Wall -g -MP -MD -fPIC -DMTCR_API= -DMST_UL -g -O2 -DNO_RDMEM -DMST_UL -MT libmtcr_ul_la-mtcr_mem_ops.lo -MD -MP -MF .deps/libmtcr_ul_la-mtcr_mem_ops.Tpo -c mtcr_mem_ops.c -o libmtcr_ul_la-mtcr_mem_ops.o >/dev/null 2>&1
make[2]: *** [Makefile:623: libmtcr_ul_la-fwctrl.lo] Error 1
```

**Comment by ich777** [comment]
Same on Slackware current:
```
make[1]: *** [Makefile:538: all-recursive] Error 1
make: *** [Makefile:422: all] Error 2
fwctrl.c: In function 'fwctl_control_access_register':
fwctrl.c:190:27: error: implicit declaration of function 'return_by_reg_status' [-Wimplicit-function-declaration]
  190 |             *reg_status = return_by_reg_status(cmd_status);
      |                           ^~~~~~~~~~~~~~~~~~~~
In file included from fwctrl.c:45:
fwctrl.c:195:56: error: implicit declaration of function 'm_err2str' [-Wimplicit-function-declaration]
  195 |                       reg_id, cmd_status, *reg_status, m_err2str(status));
      |                                                        ^~~~~~~~~
../include/mtcr_ul/fwctrl_ioctl.h:47:81: note: in definition of macro 'FWCTL_DEBUG_PRINT'
   47 |         printf("%s: %s %d: " format, FWCTL_ENV_VAR_DEBUG, __func__, __LINE__, ##arg); \
      |                                                                                 ^~~
../include/mtcr_ul/fwctrl_ioctl.h:47:16: warning: format '%s' expects argument of type 'char *', but argument 8 has type 'int' [-Wformat=]
   47 |         printf("%s: %s %d: " format, FWCTL_ENV_VAR_DEBUG, __func__, __LINE__, ##arg); \
      |                ^~~~~~~~~~~~~
fwctrl.c:194:5: note: in expansion of macro 'FWCTL_DEBUG_PRINT'
  194 |     FWCTL_DEBUG_PRINT(mf, "register id = 0x%x, command status = 0x%x, reg status code: 0x%x, reg status: %s\n",
      |     ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:589: libmtcr_ul_la-fwctrl.lo] Error 1
make: *** [Makefile:538: install-recursive] Error 1
```

However on Slackware 15 it compiles just fine.

**Comment by k0ste** [comment]
> Same error building on Arch Linux

[Added](https://aur.archlinux.org/cgit/aur.git/commit/?h=mstflint&id=540072d0efbbb8c968a9fe33a72f59b55e004849) patch from #1131

**Comment by ich777** [comment]
Can confirm that PR #1131 solves the compilation error.

**Comment by gobenji** [comment]
In RHEL-58081, Kamal Heib from Red Hat asks:

> Could you please check with the MFT team when they plan to release an official release that includes the changes for supporting mstfwmanager?

(he means the changes from #1131)

@ogalbxela Can you share around what time the next release of mstflint is planned?

**Comment by ogalbxela** [comment]
> 
> [@ogalbxela](https://github.com/ogalbxela) Can you share around what time the next release of mstflint is planned?

The next release will be issued in early May.

**Comment by gobenji** [comment]
mstflint-4.32.0 builds on RHEL-10.0 (GA).
